[package]
name = "steganography"
version = "0.1.0"
edition = "2024"

[dependencies]
image = "0.25.6"
rand = "0.9.2"
sha2 = "0.11.0-rc.0"
rand_chacha = "0.9.0"
clap = { version = "4.5.43", features = ["derive"] }
anyhow = "1.0.98"
base64 = "0.22.1"
flate2 = "1.1.2"
